spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Git-GG/config.git
          username: 15890194185@163.com
          password: git123456.0
  application:
    name: config



eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8762