spring:
  application:
    name: customer

  datasource:
    name: mysql_ywstore
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/yw_store?zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
eureka:
  client:
    serviceUrl:
     defaultZone: http://127.0.0.1:8761/eureka/

mybatis:
  mapper-locations: classpath:com.feng.customer.mapper/*.xml
    #自动定义别名
  type-aliases-package: com.feng.customer.model
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true

  #pagehelper
pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql

#项目相关配置
server:
  servlet:
    context-path: /estore
  port: 8088