package com.feng.product_api.domain;

import lombok.Data;

/**
 * @author bee
 * @create 2019-04-19 13:33
 * @desc
 **/
@Data
public class YwProductsVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.product_sn
     *
     * @mbg.generated
     */
    private String productSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

}
