package com.feng.product.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class TbYwProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.product_sn
     *
     * @mbg.generated
     */
    private String productSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.product_qrcode
     *
     * @mbg.generated
     */
    private String productQrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.first_attributes_name
     *
     * @mbg.generated
     */
    private String firstAttributesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.second_attributes_name
     *
     * @mbg.generated
     */
    private String secondAttributesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.is_distribution
     *
     * @mbg.generated
     */
    private Boolean isDistribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.is_shelf
     *
     * @mbg.generated
     */
    private Boolean isShelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.is_promotion
     *
     * @mbg.generated
     */
    private Boolean isPromotion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.create_date
     *
     * @mbg.generated
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.update_date
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_yw_product.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.product_id
     *
     * @return the value of tb_yw_product.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.product_id
     *
     * @param productId the value for tb_yw_product.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.product_sn
     *
     * @return the value of tb_yw_product.product_sn
     *
     * @mbg.generated
     */
    public String getProductSn() {
        return productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.product_sn
     *
     * @param productSn the value for tb_yw_product.product_sn
     *
     * @mbg.generated
     */
    public void setProductSn(String productSn) {
        this.productSn = productSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.title
     *
     * @return the value of tb_yw_product.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.title
     *
     * @param title the value for tb_yw_product.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.shop_name
     *
     * @return the value of tb_yw_product.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.shop_name
     *
     * @param shopName the value for tb_yw_product.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.product_qrcode
     *
     * @return the value of tb_yw_product.product_qrcode
     *
     * @mbg.generated
     */
    public String getProductQrcode() {
        return productQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.product_qrcode
     *
     * @param productQrcode the value for tb_yw_product.product_qrcode
     *
     * @mbg.generated
     */
    public void setProductQrcode(String productQrcode) {
        this.productQrcode = productQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.weight
     *
     * @return the value of tb_yw_product.weight
     *
     * @mbg.generated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.weight
     *
     * @param weight the value for tb_yw_product.weight
     *
     * @mbg.generated
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.first_attributes_name
     *
     * @return the value of tb_yw_product.first_attributes_name
     *
     * @mbg.generated
     */
    public String getFirstAttributesName() {
        return firstAttributesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.first_attributes_name
     *
     * @param firstAttributesName the value for tb_yw_product.first_attributes_name
     *
     * @mbg.generated
     */
    public void setFirstAttributesName(String firstAttributesName) {
        this.firstAttributesName = firstAttributesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.second_attributes_name
     *
     * @return the value of tb_yw_product.second_attributes_name
     *
     * @mbg.generated
     */
    public String getSecondAttributesName() {
        return secondAttributesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.second_attributes_name
     *
     * @param secondAttributesName the value for tb_yw_product.second_attributes_name
     *
     * @mbg.generated
     */
    public void setSecondAttributesName(String secondAttributesName) {
        this.secondAttributesName = secondAttributesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.is_distribution
     *
     * @return the value of tb_yw_product.is_distribution
     *
     * @mbg.generated
     */
    public Boolean getIsDistribution() {
        return isDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.is_distribution
     *
     * @param isDistribution the value for tb_yw_product.is_distribution
     *
     * @mbg.generated
     */
    public void setIsDistribution(Boolean isDistribution) {
        this.isDistribution = isDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.is_shelf
     *
     * @return the value of tb_yw_product.is_shelf
     *
     * @mbg.generated
     */
    public Boolean getIsShelf() {
        return isShelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.is_shelf
     *
     * @param isShelf the value for tb_yw_product.is_shelf
     *
     * @mbg.generated
     */
    public void setIsShelf(Boolean isShelf) {
        this.isShelf = isShelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.is_promotion
     *
     * @return the value of tb_yw_product.is_promotion
     *
     * @mbg.generated
     */
    public Boolean getIsPromotion() {
        return isPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.is_promotion
     *
     * @param isPromotion the value for tb_yw_product.is_promotion
     *
     * @mbg.generated
     */
    public void setIsPromotion(Boolean isPromotion) {
        this.isPromotion = isPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.create_date
     *
     * @return the value of tb_yw_product.create_date
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.create_date
     *
     * @param createDate the value for tb_yw_product.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.update_date
     *
     * @return the value of tb_yw_product.update_date
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.update_date
     *
     * @param updateDate the value for tb_yw_product.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_yw_product.description
     *
     * @return the value of tb_yw_product.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_yw_product.description
     *
     * @param description the value for tb_yw_product.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productSn=").append(productSn);
        sb.append(", title=").append(title);
        sb.append(", shopName=").append(shopName);
        sb.append(", productQrcode=").append(productQrcode);
        sb.append(", weight=").append(weight);
        sb.append(", firstAttributesName=").append(firstAttributesName);
        sb.append(", secondAttributesName=").append(secondAttributesName);
        sb.append(", isDistribution=").append(isDistribution);
        sb.append(", isShelf=").append(isShelf);
        sb.append(", isPromotion=").append(isPromotion);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbYwProduct other = (TbYwProduct) that;
        return (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getProductSn() == null ? other.getProductSn() == null : this.getProductSn().equals(other.getProductSn()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getShopName() == null ? other.getShopName() == null : this.getShopName().equals(other.getShopName()))
            && (this.getProductQrcode() == null ? other.getProductQrcode() == null : this.getProductQrcode().equals(other.getProductQrcode()))
            && (this.getWeight() == null ? other.getWeight() == null : this.getWeight().equals(other.getWeight()))
            && (this.getFirstAttributesName() == null ? other.getFirstAttributesName() == null : this.getFirstAttributesName().equals(other.getFirstAttributesName()))
            && (this.getSecondAttributesName() == null ? other.getSecondAttributesName() == null : this.getSecondAttributesName().equals(other.getSecondAttributesName()))
            && (this.getIsDistribution() == null ? other.getIsDistribution() == null : this.getIsDistribution().equals(other.getIsDistribution()))
            && (this.getIsShelf() == null ? other.getIsShelf() == null : this.getIsShelf().equals(other.getIsShelf()))
            && (this.getIsPromotion() == null ? other.getIsPromotion() == null : this.getIsPromotion().equals(other.getIsPromotion()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductSn() == null) ? 0 : getProductSn().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getShopName() == null) ? 0 : getShopName().hashCode());
        result = prime * result + ((getProductQrcode() == null) ? 0 : getProductQrcode().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result + ((getFirstAttributesName() == null) ? 0 : getFirstAttributesName().hashCode());
        result = prime * result + ((getSecondAttributesName() == null) ? 0 : getSecondAttributesName().hashCode());
        result = prime * result + ((getIsDistribution() == null) ? 0 : getIsDistribution().hashCode());
        result = prime * result + ((getIsShelf() == null) ? 0 : getIsShelf().hashCode());
        result = prime * result + ((getIsPromotion() == null) ? 0 : getIsPromotion().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static TbYwProduct.Builder builder() {
        return new TbYwProduct.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private TbYwProduct obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new TbYwProduct();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.product_id
         *
         * @param productId the value for tb_yw_product.product_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder productId(Integer productId) {
            obj.setProductId(productId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.product_sn
         *
         * @param productSn the value for tb_yw_product.product_sn
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder productSn(String productSn) {
            obj.setProductSn(productSn);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.title
         *
         * @param title the value for tb_yw_product.title
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder title(String title) {
            obj.setTitle(title);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.shop_name
         *
         * @param shopName the value for tb_yw_product.shop_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder shopName(String shopName) {
            obj.setShopName(shopName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.product_qrcode
         *
         * @param productQrcode the value for tb_yw_product.product_qrcode
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder productQrcode(String productQrcode) {
            obj.setProductQrcode(productQrcode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.weight
         *
         * @param weight the value for tb_yw_product.weight
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder weight(String weight) {
            obj.setWeight(weight);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.first_attributes_name
         *
         * @param firstAttributesName the value for tb_yw_product.first_attributes_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder firstAttributesName(String firstAttributesName) {
            obj.setFirstAttributesName(firstAttributesName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.second_attributes_name
         *
         * @param secondAttributesName the value for tb_yw_product.second_attributes_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder secondAttributesName(String secondAttributesName) {
            obj.setSecondAttributesName(secondAttributesName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.is_distribution
         *
         * @param isDistribution the value for tb_yw_product.is_distribution
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isDistribution(Boolean isDistribution) {
            obj.setIsDistribution(isDistribution);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.is_shelf
         *
         * @param isShelf the value for tb_yw_product.is_shelf
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isShelf(Boolean isShelf) {
            obj.setIsShelf(isShelf);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.is_promotion
         *
         * @param isPromotion the value for tb_yw_product.is_promotion
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isPromotion(Boolean isPromotion) {
            obj.setIsPromotion(isPromotion);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.create_date
         *
         * @param createDate the value for tb_yw_product.create_date
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createDate(LocalDateTime createDate) {
            obj.setCreateDate(createDate);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.update_date
         *
         * @param updateDate the value for tb_yw_product.update_date
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateDate(LocalDateTime updateDate) {
            obj.setUpdateDate(updateDate);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tb_yw_product.description
         *
         * @param description the value for tb_yw_product.description
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder description(String description) {
            obj.setDescription(description);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public TbYwProduct build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        productId("product_id", "productId", "INTEGER", false),
        productSn("product_sn", "productSn", "VARCHAR", false),
        title("title", "title", "VARCHAR", false),
        shopName("shop_name", "shopName", "VARCHAR", false),
        productQrcode("product_qrcode", "productQrcode", "VARCHAR", false),
        weight("weight", "weight", "VARCHAR", false),
        firstAttributesName("first_attributes_name", "firstAttributesName", "VARCHAR", false),
        secondAttributesName("second_attributes_name", "secondAttributesName", "VARCHAR", false),
        isDistribution("is_distribution", "isDistribution", "BIT", false),
        isShelf("is_shelf", "isShelf", "BIT", false),
        isPromotion("is_promotion", "isPromotion", "BIT", false),
        createDate("create_date", "createDate", "TIMESTAMP", false),
        updateDate("update_date", "updateDate", "TIMESTAMP", false),
        description("description", "description", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tb_yw_product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}