package com.feng.product.mapper;

import com.feng.product.model.TbProductCategory;
import com.feng.product.model.TbProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    long countByExample(TbProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    int deleteByExample(TbProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer productCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    int insert(TbProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    int insertSelective(TbProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbProductCategory selectOneByExample(TbProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbProductCategory selectOneByExampleSelective(@Param("example") TbProductCategoryExample example, @Param("selective") TbProductCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TbProductCategory> selectByExampleSelective(@Param("example") TbProductCategoryExample example, @Param("selective") TbProductCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    List<TbProductCategory> selectByExample(TbProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbProductCategory selectByPrimaryKeySelective(@Param("productCategoryId") Integer productCategoryId, @Param("selective") TbProductCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    TbProductCategory selectByPrimaryKey(Integer productCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbProductCategory record, @Param("example") TbProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbProductCategory record, @Param("example") TbProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbProductCategory record);
}