package com.feng.product.mapper;

import com.feng.product.model.TbProductImage;
import com.feng.product.model.TbProductImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbProductImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    long countByExample(TbProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    int deleteByExample(TbProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer productImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    int insert(TbProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    int insertSelective(TbProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbProductImage selectOneByExample(TbProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbProductImage selectOneByExampleSelective(@Param("example") TbProductImageExample example, @Param("selective") TbProductImage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TbProductImage> selectByExampleSelective(@Param("example") TbProductImageExample example, @Param("selective") TbProductImage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    List<TbProductImage> selectByExample(TbProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbProductImage selectByPrimaryKeySelective(@Param("productImageId") Integer productImageId, @Param("selective") TbProductImage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    TbProductImage selectByPrimaryKey(Integer productImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbProductImage record, @Param("example") TbProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbProductImage record, @Param("example") TbProductImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbProductImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbProductImage record);
}