package com.feng.product.mapper;

import com.feng.product.model.TbYwProduct;
import com.feng.product.model.TbYwProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TbYwProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    long countByExample(TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int deleteByExample(TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int insert(TbYwProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int insertSelective(TbYwProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbYwProduct selectOneByExample(TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbYwProduct selectOneByExampleSelective(@Param("example") TbYwProductExample example, @Param("selective") TbYwProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbYwProduct selectOneByExampleWithBLOBs(TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TbYwProduct> selectByExampleSelective(@Param("example") TbYwProductExample example, @Param("selective") TbYwProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    List<TbYwProduct> selectByExampleWithBLOBs(TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    List<TbYwProduct> selectByExample(TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbYwProduct selectByPrimaryKeySelective(@Param("productId") Integer productId, @Param("selective") TbYwProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    TbYwProduct selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbYwProduct record, @Param("example") TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TbYwProduct record, @Param("example") TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbYwProduct record, @Param("example") TbYwProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbYwProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TbYwProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_yw_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbYwProduct record);
}